name: BBSToper
main: com.mcsunnyside.BBSToper.Main
version: 1.1
commands:
    poster:
        description: BBSToper的主要指令.
permissions:
    poster.admin:
        description: 管理员权限.
        default: op